#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=11

# Run from the repo root so .env lands next to package.json.
cd "$(dirname "$0")/.."

banner "MovieFlix local setup: TMDB + Appwrite"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "TMDB: API read access token"
say "The app calls TMDB with a Bearer token (services/api.ts)."
open_url "https://www.themoviedb.org/settings/api"
step "Sign in (or sign up), then request an API key if you don't have one yet."
step "On the API settings page, copy the long 'API Read Access Token' (starts eyJ...)."
note "Use the read access token, not the short 'API Key'; the app sends it as a Bearer token."
ask_secret EXPO_PUBLIC_MOVIE_API_KEY "Paste the API Read Access Token:"
write_env EXPO_PUBLIC_MOVIE_API_KEY "$EXPO_PUBLIC_MOVIE_API_KEY"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Appwrite: project"
say "Appwrite stores the Trending search counts."
open_url "https://cloud.appwrite.io/console"
step "Create a project (or open your existing one), e.g. named 'MovieFlix'."
step "Open the project's Settings (or Overview) page: it shows the Project ID and API Endpoint."
ask EXPO_PUBLIC_APPWRITE_PROJECT_NAME "Project name:"
ask EXPO_PUBLIC_APPWRITE_PROJECT_ID "Project ID:"
note "The endpoint is region-specific, e.g. https://fra.cloud.appwrite.io/v1"
ask EXPO_PUBLIC_APPWRITE_ENDPOINT "API Endpoint:"
write_env EXPO_PUBLIC_APPWRITE_PROJECT_NAME "$EXPO_PUBLIC_APPWRITE_PROJECT_NAME"
write_env EXPO_PUBLIC_APPWRITE_PROJECT_ID "$EXPO_PUBLIC_APPWRITE_PROJECT_ID"
write_env EXPO_PUBLIC_APPWRITE_ENDPOINT "$EXPO_PUBLIC_APPWRITE_ENDPOINT"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Appwrite: register the app platform"
say "Appwrite rejects client requests from apps it doesn't know about."
step "In the project, find 'Add platform' (on Overview, under Integrations/Platforms)."
step "Choose Android, then add the package name:  host.exp.exponent"
step "Choose Apple/iOS, then add the bundle ID:     host.exp.exponent"
note "host.exp.exponent is Expo Go's ID. For a development build, use your own package/bundle ID instead."
pause "Press Enter once the platform(s) are added"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Appwrite: database"
step "In the project sidebar, open Databases and click Create database."
step "Name it anything (e.g. 'movies'), then open it and copy its Database ID."
ask EXPO_PUBLIC_APPWRITE_DATABASE_ID "Database ID:"
write_env EXPO_PUBLIC_APPWRITE_DATABASE_ID "$EXPO_PUBLIC_APPWRITE_DATABASE_ID"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Appwrite: collection + attributes"
note "Newer consoles call collections 'Tables' and attributes 'Columns'; they're the same thing."
step "Inside the database, create a collection named 'metrics' (any name works)."
step "Add these attributes, all Required:"
say  "    searchTerm   String   size 255"
say  "    movie_id     Integer"
say  "    title        String   size 255"
say  "    count        Integer"
say  "    poster_url   URL"
note "Names are case-sensitive: they must match services/appwrite.ts exactly."
step "Copy the collection's ID from its settings/header."
ask EXPO_PUBLIC_APPWRITE_COLLECTION_ID "Collection ID:"
write_env EXPO_PUBLIC_APPWRITE_COLLECTION_ID "$EXPO_PUBLIC_APPWRITE_COLLECTION_ID"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Appwrite: unique index on searchTerm"
say "This stops two concurrent first searches from creating duplicate rows."
step "In the collection, open Indexes and click Create index."
step "Key: searchTerm_unique   Type: Unique   Attribute: searchTerm (ASC)."
warn "If the collection already has duplicate searchTerm rows, the index fails. Merge or delete them first."
pause "Press Enter once the index shows as available"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Appwrite: collection permissions"
say "The app runs without a signed-in user, so the 'Any' role needs access."
step "In the collection, open Settings → Permissions → Add role → Any."
step "Tick Read, Create, and Update (leave Delete unticked), then click Update."
note "Update is required: search counts are incremented on existing rows."
pause "Press Enter once permissions are saved"

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Appwrite: email/password sign-in"
say "Members sign up and sign in with an email and password (services/session.tsx)."
step "In the project sidebar, open Auth → Settings (older consoles: Auth → Security)."
step "Under Auth methods, make sure Email/Password is enabled."
note "Email verification and password recovery aren't used yet, so no SMTP or redirect setup is needed."
pause "Press Enter once Email/Password is enabled"

# ── 9 ────────────────────────────────────────────────────────────────────
stage "Appwrite: saved-movies collection + attributes"
say "Each Member's Saved list lives in its own collection (services/savedMovies.ts)."
step "In the same database, create a collection named 'saved_movies' (any name works)."
step "Add these attributes:"
say  "    member_id      String    size 36    Required"
say  "    movie_id       Integer              Required"
say  "    title          String    size 255   Required"
say  "    poster_url     URL                  Optional"
say  "    release_year   Integer              Optional"
say  "    rating         Float                Required"
note "Names are case-sensitive: they must match services/savedMovies.ts exactly."
step "Copy the collection's ID from its settings/header."
ask EXPO_PUBLIC_APPWRITE_SAVED_COLLECTION_ID "Saved-movies collection ID:"
write_env EXPO_PUBLIC_APPWRITE_SAVED_COLLECTION_ID "$EXPO_PUBLIC_APPWRITE_SAVED_COLLECTION_ID"

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Appwrite: saved-movies privacy + unique index"
say "Each Saved Movie is readable only by the Member who saved it, and saved at most once."
step "In the saved_movies collection, open Settings → Document security and turn it ON."
step "Still in Settings → Permissions → Add role → Users (not Any)."
step "Tick Create only (leave Read, Update, Delete unticked), then click Update."
note "The app gives each Saved Movie read/update/delete for its own Member when it saves it."
step "Open Indexes → Create index."
step "Key: member_movie_unique   Type: Unique   Attributes: member_id (ASC), movie_id (ASC)."
warn "Never add Read for Any or Users here: it would show every Member's Saved list to everyone."
pause "Press Enter once document security, permissions, and the index are saved"

# ── 11 ───────────────────────────────────────────────────────────────────
stage "Smoke check"
say "Your .env now holds every EXPO_PUBLIC_* value the app reads."
if confirm "Run the test suite now (npm test)?"; then
  npm test || warn "tests failed; see the output above"
  pause
fi
say "Start the app with:  npx expo start"
step "Home should list popular movies (TMDB works)."
step "Search a title and tap a result. It should then appear under Trending on Home (Appwrite works)."
step "On Profile, tap Create account and sign up. Profile should show your name and email (Auth works)."
step "Close and reopen the app: Profile should still show you signed in."
step "Sign out, then tap Sign in with the same email and password: Profile should show you again."
step "Open a movie and tap Save (the bookmark icon). Go back and reopen it: the icon should still be filled (Saved Movies work)."
note "Expo only reads .env at startup: restart it after changing values."
pause "Press Enter to finish"

finish
